### ISSUE TITLE
[Question] Can I use some of your ideas?

### ISSUE THREAD

**Issue by josh18** [joel1st/championweb#14]
I'm thinking of starting a project that analyzes myself so that I can see my strengths and weakness (haven't looked at the API yet so still got to see if this is possible). Is it all right if I use some of your ideas such as the graphs and item builds?

For now I'm just building it for myself but if I end up making something decent I would like to make it available to other people.

**Comment by Aaron-Hartwig** [comment]
@josh18 If you decide this is possible via the API, why not just build it into the existing championweb platform?

**Comment by josh18** [comment]
@Aaron-Hartwig Well it will be serving a different purpose, focusing on the summoner instead of the champion. I'm also not sure how @joel1st would feel about it.

How do you collate all your data? I can't see a way to do it in the API.

**Comment by rivertam** [comment]
If he doesn't want it, he won't accept the pull request, and you can keep it as a fork.

The data collation wasn't version controlled last time I checked, but that was months ago.

**Comment by libnani** [comment]
@josh18 that sounds like a great idea, I second that motion
