### ISSUE TITLE
API

### ISSUE THREAD

**Issue by mps** [joel1st/championweb#21]
Any plans to make your data available via an API?  This site would look good as an iOS app :)

**Comment by irae** [comment]
If you read through the code, there is kinda already an API. His mongo DB stuff also helps. The only thing it needs to do is to provide a JSON dump of the mongo DB each patch and the iOS app could work.

I think the model here would be partnership. Open source app, same old DB on the repo, but whoever partners with him and makes the app, get's updated DB dump as JSON for the app each patch and shares revenue. =)

I don't even know the owner, I am just brainstorming here, as I thought the same you did.

**Comment by pfugate** [comment]
There is now an api that you can use. Check out api.champion.gg.

**Comment by abaltra** [comment]
Marking this as closed.
