### ISSUE TITLE
API

### ISSUE THREAD

**Issue by decanus** [joel1st/championweb#25]
Is there any way there could be a REST API, I think this would be an awesome tool. I would like to use your data, but currently don't see a nice way. And I think importing the dumps would be rather stupid.

Some proposed methods:

GET /champions
GET /champions/{name}
GET /champions/{name}/kill
GET /champions/{name}?against={otherChamp} for win rate against champ.

I'd be happy to help you implement it.

**Comment by pfugate** [comment]
There is now an api that you can use. Check out api.champion.gg.

**Comment by abaltra** [comment]
Marking this as closed.
