### ISSUE TITLE
Wukong Profile Picture

### ISSUE THREAD

**Issue by OneebMalik** [joel1st/championweb#35]
Wukong's profile picture no longer shows up. It's replaced by a cyan square. "/public/champion.jpg" and "/public/small_champion.jpg" also show a cyan square where Wukong is supposed to be.

**Comment by corylulu** [comment]
https://github.com/joel1st/championweb/pull/33

I submitted a fix for it here, he's just gotta pull it. The image is actually incorrect because Riot screwed up, not him (he pulls the image from ddragon api), but this would at least prevents it from filling the screen on.

**Comment by OneebMalik** [comment]
Ok that's great! Yeah I assumed it was Riot's API. The champion portraits aren't stored locally.
