### ISSUE TITLE
Support OpenSearch

### ISSUE THREAD

**Issue by ngryman** [joel1st/championweb#54]
Hi,

Would be nice to be able to search a champion in the browser address bar directly, like this:

![opensearch](https://cloud.githubusercontent.com/assets/892048/16567288/179b1b5e-421d-11e6-8b7b-6f1c1c323b9f.gif)

This can be achieved pretty easily with OpenSearch: http://www.opensearch.org/Home. I can make a PR if you want.

Thanks!

**Comment by joel1st** [comment]
Hey, I've added this- It's in master - will be released as part of next deploy.

**Comment by ngryman** [comment]
Awesome!

**Comment by ngryman** [comment]
I see it in production, closing it for you.
