### ISSUE TITLE
API data not updated

### ISSUE THREAD

**Issue by jjmaldonis** [joel1st/championweb#58]
I believe the data I am pulling from the API is outdated by quite a bit. I'm pulling down the general data, for example:

```
http://api.champion.gg/champion/Soraka/general?api_key=
```

and I'm getting these results for Soraka:

```
"play_percent": {
    "change": -1,
    "position": 9,
    "val": 9.37
},
"win_percent": {
    "change": 1,
    "position": 8,
    "val": 51.96
}
```

Comparing these numbers to the numbers currently on champion.gg, along with data from other champions, it looks like the data I am pulling from the API is at ~ patch 6.12, which is quite a bit old.

Let me know if something isn't clear and I'll update this.

**Comment by dnlbauer** [comment]
I observe this too. The data seems to not have updated for some weeks. Counterpicks are outdated and Kled isnt available for any call.

**Comment by abaltra** [comment]
Yup, our bad. Was caused by some legacy code using an old database. Data's updated now.
