### ISSUE TITLE
[API question] How to retrieve the patch version from the Champion.gg API ?

### ISSUE THREAD

**Issue by Ilshidur** [joel1st/championweb#60]
All in the title.

I expected a `patch` field from the `http://api.champion.gg/champion` endpoints, but I couldn't find a way to retrieve it.

**Comment by abaltra** [comment]
Hi!
You can get the patch version of the game the aggregate data's from `http://api.champion.gg/stats/overall`. Currently the results of the endpoint are:

```
{
  id: 1,
  patch: 6.2,
  championsAnalyzed: "1,174,630",
  patchHistory: [
    6.16,
    6.17,
    6.18,
    6.19,
    6.2
  ]
}
```

The patch number isn't in the champions information, so if it's required, a different call will have to be made.

Cheers!

**Comment by abaltra** [comment]
One thing we did notice though is that the versions are being treated as numbers (hence why it shows `6.2` instead of `6.20`). That's going to be fixed in the next production push.

**Comment by Ilshidur** [comment]
Thank you very much !

I also just wanted to make you know that this endpoints is undocumented in the 0.0.1 API.

Keep up your awesome work !
