### ISSUE TITLE
Inconsistent Data 

### ISSUE THREAD

**Issue by shadowfyren** [joel1st/championweb#8]
Take Caitlyn and Sona duo for example. 

On Caitlyn's page, Sona is under "Poor Synergy":
![sona1](https://cloud.githubusercontent.com/assets/10970992/6275778/dec0d36c-b84f-11e4-9632-1f65441b348b.PNG)

But on the matchup page (http://champion.gg/matchup/Sona/Caitlyn/synergy), it says they have strong synergy:
![sona2](https://cloud.githubusercontent.com/assets/10970992/6275797/0a786b0a-b850-11e4-91bf-da1687d11e3c.PNG)

I'll take a look into what's causing this bug.

**Comment by joel1st** [comment]
Thought this was a caching issue as it's working on my local instance, will look into why this is happening.

**Comment by joel1st** [comment]
Just letting you know it's fixed up now!
